// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// WARNING! Do not edit this file manually, your changes will be overwritten.

#pragma once

#ifndef MUTATIONOBJECT_H
#define MUTATIONOBJECT_H

#include "TestServerSchema.h"

namespace graphql::test_server::object {
namespace methods::MutationHas {

template <class TImpl>
concept applyMutationTelemetryWithParams = requires (TImpl impl, service::FieldParams params, int sensorIdArg, double sensorValueArg)
{
	{ service::AwaitableScalar<std::optional<bool>> { impl.applyMutationTelemetry(std::move(params), std::move(sensorIdArg), std::move(sensorValueArg)) } };
};

template <class TImpl>
concept applyMutationTelemetry = requires (TImpl impl, int sensorIdArg, double sensorValueArg)
{
	{ service::AwaitableScalar<std::optional<bool>> { impl.applyMutationTelemetry(std::move(sensorIdArg), std::move(sensorValueArg)) } };
};

template <class TImpl>
concept beginSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.beginSelectionSet(params) };
};

template <class TImpl>
concept endSelectionSet = requires (TImpl impl, const service::SelectionSetParams params)
{
	{ impl.endSelectionSet(params) };
};

} // namespace methods::MutationHas

class [[nodiscard("unnecessary construction")]] Mutation final
	: public service::Object
{
private:
	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolveMutationTelemetry(service::ResolverParams&& params) const;

	[[nodiscard("unnecessary call")]] service::AwaitableResolver resolve_typename(service::ResolverParams&& params) const;

	struct [[nodiscard("unnecessary construction")]] Concept
	{
		virtual ~Concept() = default;

		virtual void beginSelectionSet(const service::SelectionSetParams& params) const = 0;
		virtual void endSelectionSet(const service::SelectionSetParams& params) const = 0;

		[[nodiscard("unnecessary call")]] virtual service::AwaitableScalar<std::optional<bool>> applyMutationTelemetry(service::FieldParams&& params, int&& sensorIdArg, double&& sensorValueArg) const = 0;
	};

	template <class T>
	struct [[nodiscard("unnecessary construction")]] Model final
		: Concept
	{
		explicit Model(std::shared_ptr<T> pimpl) noexcept
			: _pimpl { std::move(pimpl) }
		{
		}

		[[nodiscard("unnecessary call")]] service::AwaitableScalar<std::optional<bool>> applyMutationTelemetry(service::FieldParams&& params, int&& sensorIdArg, double&& sensorValueArg) const override
		{
			if constexpr (methods::MutationHas::applyMutationTelemetryWithParams<T>)
			{
				return { _pimpl->applyMutationTelemetry(std::move(params), std::move(sensorIdArg), std::move(sensorValueArg)) };
			}
			else if constexpr (methods::MutationHas::applyMutationTelemetry<T>)
			{
				return { _pimpl->applyMutationTelemetry(std::move(sensorIdArg), std::move(sensorValueArg)) };
			}
			else
			{
				throw service::unimplemented_method(R"ex(Mutation::applyMutationTelemetry)ex");
			}
		}

		void beginSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::MutationHas::beginSelectionSet<T>)
			{
				_pimpl->beginSelectionSet(params);
			}
		}

		void endSelectionSet(const service::SelectionSetParams& params) const override
		{
			if constexpr (methods::MutationHas::endSelectionSet<T>)
			{
				_pimpl->endSelectionSet(params);
			}
		}

	private:
		const std::shared_ptr<T> _pimpl;
	};

	explicit Mutation(std::unique_ptr<const Concept> pimpl) noexcept;

	[[nodiscard("unnecessary call")]] service::TypeNames getTypeNames() const noexcept;
	[[nodiscard("unnecessary call")]] service::ResolverMap getResolvers() const noexcept;

	void beginSelectionSet(const service::SelectionSetParams& params) const override;
	void endSelectionSet(const service::SelectionSetParams& params) const override;

	const std::unique_ptr<const Concept> _pimpl;

public:
	template <class T>
	explicit Mutation(std::shared_ptr<T> pimpl) noexcept
		: Mutation { std::unique_ptr<const Concept> { std::make_unique<Model<T>>(std::move(pimpl)) } }
	{
	}

	[[nodiscard("unnecessary call")]] static constexpr std::string_view getObjectType() noexcept
	{
		return { R"gql(Mutation)gql" };
	}
};

} // namespace graphql::test_server::object

#endif // MUTATIONOBJECT_H
